### ISSUE TITLE
Open directly to Extensions preference pane

### ISSUE THREAD

**Issue by homebysix** [cdzombak/finder-atom#1]
Might there be a way to open System Preferences directly to the "Extensions" pane?

Perhaps something like [this](https://github.com/hbang/TermHere/blob/master/TermHere/ViewController.swift#L90).

**Comment by cdzombak** [comment]
Ah, cool. I'd been trying to open it via the URL scheme (`x-apple.systempreferences://com.apple.preferences.extensions`) but it seems like that stopped working on OS X 10.11 — I'll try this.

**Comment by cdzombak** [comment]
[v1.1](https://github.com/cdzombak/finder-atom/tree/v1.1) addresses this.

**Comment by homebysix** [comment]
Fantastic! 👏
