### ISSUE TITLE
Clicking on Finder toolbar icon does nothing

### ISSUE THREAD

**Issue by quyin** [cdzombak/finder-atom#3]
This is the app I've been looking for!

I just installed v1.2, on macOS Sierra 10.12.4 running Atom 1.16.0.

The app itself opens, showing a window about enabling Extension permission in System Preferences. I followed through.

However, clicking on the "Open Directory in Atom" Finder toolbar icon does nothing.

Logging out / rebooting doesn't solve the problem.

I'm not sure where to look for logs, though. If logs could help I'd be glad to provide it.

**Comment by quyin** [comment]
I just noticed that it was tested on 10.11.6. So maybe a compatibility issue?

**Comment by cdzombak** [comment]
> However, clicking on the "Open Directory in Atom" Finder toolbar icon does nothing.

Do you see this menu when you click on the icon? Or does truly nothing happen?

<img width="193" alt="screen shot 2017-05-02 at 12 49 12" src="https://cloud.githubusercontent.com/assets/102904/25628952/ef3fd558-2f35-11e7-9e39-ff847a0e9479.png">

**Comment by cdzombak** [comment]
_Note to self:_ https://github.com/hbang/TermHere/issues/9 seems possibly-related.

**Comment by quyin** [comment]
@cdzombak Yes, I see the menu, exactly as your screenshot. However clicking on "Open Directory in Atom" menu item does nothing. Sorry that I wasn't clear enough.

**Comment by cdzombak** [comment]
That makes more sense.

@quyin Where do you have Atom installed? On my system it's in `/Applications/Atom.app` — is your system any different?

**Comment by quyin** [comment]
@cdzombak It's also at `/Applications/Atom.app`.

I tried on a different computer (a late 2015 iMac, also running macOS Sierra 10.12.4), and it's the same problem.

**Comment by nickv2002** [comment]
Thanks for making this tool. It's also exactly what I was looking for. :-)
Unfortunately, I'm having the same issue as @quyin on Sierra 10.12.5. Can see the menu but clicking it does nothing.

Any log files etc that I could upload to help diagnose?

**Comment by nickv2002** [comment]
Since @cdzombak solution isn't working at the moment, I whipped up an AppleScript app that accomplishes this same task. Give it a try and let me know if it works for you. You can add it to your Finder Toolbar via a _Command-Drag_ action (seems like you have to hold Command before starting the drag FWIW).

I'm not sure if the code signing will work but if it doesn't work for any reason (or if you're just curious what it does) you can open it with `/Applications/Utilities/Script Editor.app` and run/modify/export it from there.

[AtomHere.app.zip](https://github.com/cdzombak/finder-atom/files/1117348/AtomHere.app.zip)

**Comment by quyin** [comment]
@nickv2002 Code signature doesn't work on my machine. Crash report says:

```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

I was able to export a runnable version from Script Editor, though, and it works like a charm.

Thanks!

**Comment by cdzombak** [comment]
@quyin @nickv2002 I'm working on a macOS 10.12.5 laptop now and I was seeing this same problem. I rebuilt the app in Xcode — making no changes — and the new build is working on my machine. Could you please try [this build](https://www.dropbox.com/s/b8ols6u4hdmc6o7/Open%20in%20Atom%20for%20Finder%202017-07-01%2019-39-28.zip?dl=0), and see if it works?

**Comment by quyin** [comment]
@cdzombak just tried it but it still doesn't take any effects.

given that it works on your computer but not mine, could it be code-signing related? is there any way to see a crash report or log, so that we can either confirm this or rule it out?

**Comment by cdzombak** [comment]
> given that it works on your computer but not mine, could it be code-signing related?

I doubt it; I signed that build with a Developer ID just as I have every other distribution.

> is there any way to see a crash report or log, so that we can either confirm this or rule it out?

I don't have any specific suggestions; I would try looking through the logs in the Console app when you reproduce this error. Something _might_ show up in there.

When I have a moment I'll see if I can make a build that includes some additional logging.

**Comment by cdzombak** [comment]
Okay, try this build: https://www.dropbox.com/s/p750q5tkjp9o1hh/Open%20in%20Atom%20for%20Finder%202017-07-05%2016-59-05.zip?dl=0

When you reproduce the error, open Console.app and filter on the string "open in atom" like this:

![screen shot 2017-07-05 at 17 01 24](https://user-images.githubusercontent.com/102904/27884825-a3509498-61a3-11e7-81fa-949882639ec1.png)

Those logs might be helpful for me.

**Comment by BernhardWenzel** [comment]
Hi there

I just upgraded to Sierra 10.12.5 and now have the same problem, it used to work before. I tried the latest build you mentioned but no change, also couldn't find any related logs

One thing though: open in Atom works for the `/Applications` folder. That seems to be the only directory.

**Comment by nickv2002** [comment]
Sometimes I don't get any log when it fails, but when I do get something in console this is what I get:
```
default	00:16:21.744646 -0700	Open in Atom Finder Extension	[Error] Failed to open '/Users/nick/Downloads' with 'Atom.app'
```

**Comment by nickv2002** [comment]
@BernhardWenzel if you want to try my AppleScript version, I think it's actually a bit simpler than @cdzombak fancier version: [AtomHere.app.zip](https://github.com/cdzombak/finder-atom/files/1127028/AtomHere.app.zip) (This is unsigned so you'll have to ctrl-click open or just rebuild it yourself by opening in Script Editor.)

Super simple source code:
```
(*
	AtomHere 1.0 by Nick Vance

	`AtomHere` is an AppleScript that launches a new Atom window with a Project Root of your current Finder location.
	
	In Script Editor.app choose File -> Export this script as an applciation, then command-drag the Application to your Finder toolbar

	It relies on the atom CLI tool that is usually symlinked to `/usr/local/bin/atom`.
	If it's not working for you please check that your symlink is properly installed in your path:

	$ ll /usr/local/bin/atom
	lrwxr-xr-x 1 nick 62 Jun 29 19:10 /usr/local/bin/atom -> /Applications/Software/Atom.app/Contents/Resources/app/atom.sh*

	More details: https://stackoverflow.com/questions/22390709/how-to-open-atom-editor-from-command-line-in-os-x
*)

tell application "Finder"
	
	(*
		Determine the present working directory as alias and POSIX path.
		If the insertion location is not a folder, use its parent. This is the
		case when a file is selected in Column view (otherwise, file selections
		do not seem to be treated as the insertion location).
	*)
	set pwdAlias to insertion location as alias
	if not (exists folder pwdAlias) then
		set pwdAlias to (container of pwdAlias) as alias
	end if
	set pwd to POSIX path of pwdAlias
	
	do shell script "/usr/local/bin/atom '" & pwd & "'"
end tell
```
I actually prefer it because it only requires one click on my part rather than two.

**Comment by BernhardWenzel** [comment]
@nickv2002 works like a charm, thanks! And agreed, requires just one click so preferred :-)

**Comment by cdzombak** [comment]
@nickv2002 that's good to know; thanks.

> One thing though: open in Atom works for the `/Applications` folder. That seems to be the only directory.

@BernhardWenzel huh, that's interesting! That's what I'm seeing too, it turns out. Thanks for the info.

**Comment by cdzombak** [comment]
This appears to be due to at least one sandboxing change on Sierra. I've spent a few hours trying to make things work, and that's as much time as I can spend on this.

[The updated README](https://github.com/cdzombak/finder-atom#macos-sierra-1012-incompatibility) discusses this, and [the latest release](https://github.com/cdzombak/finder-atom/releases/tag/v2.0) contains an AppleScript based on @nickv2002's code in https://github.com/cdzombak/finder-atom/issues/3#issuecomment-313317763.
